### ISSUE TITLE
Have a question

### ISSUE THREAD

**Issue by tw-e** [r-a-y/mobile-hosts#1]
Hi,ray

@r-a-y 

1."Adguard Mobile Ads"
Can you change this filter rule?
https://kb.adguard.com/en/general/adguard-ad-filters#mobile

2.Can you manually add the rules inside?

thank you!

**Comment by r-a-y** [comment]
Hi, thanks for the ticket.

Good question, I originally intended to separate the different Adguard filters on purpose for people that want choice like I do.

The filter list that you linked to is almost the same as the ones I already offer (Adguard Mobile Ads + Adguard Mobile Spyware + Adguard Specific Apps).

However, I'm missing the Adguard Mobile General URL filter (https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/general_url.txt) and the Adguard Mobile Specific Web filter (https://github.com/AdguardTeam/AdguardFilters/blob/327aac6587c93e3589f788c0f03d75ea1780cc25/MobileFilter/sections/specific_web.txt).

If both are parsed by my converter, it only adds two additional domains:
- `cloudads-a.akamaihd.net`
- `m.yanglaopt.net`

So I thought they wouldn't be particularly useful.

Hope that helps!
