### ISSUE TITLE
[Q] AdGuard DNS + Mobile Tracking and Spyware

### ISSUE THREAD

**Issue by pidus** [r-a-y/mobile-hosts#13]
Is "AdGuard Mobile Tracking and Spyware" included in "AdGuard  DNS"  list?

**Comment by r-a-y** [comment]
Yes, Adguard Mobile Tracking and Spyware is already included in Adguard DNS:

https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/20236d412d8fcebe7dd86ed10404acb15e1523f6/configuration.json#L119-L125
