### ISSUE TITLE
It's possible add this filter list?

### ISSUE THREAD

**Issue by peter9811** [r-a-y/mobile-hosts#14]
I use AdAway for now I'm now sure to use AdGuard, I think consume a lot of battery...

But on some webs, show a pop-up about the adblock

I found this DNS filter list: https://github.com/Cybo1927/Hosts/blob/master/Hosts

Thanks

**Comment by peter9811** [comment]
I tried, but show this error... 

`Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in D:\Documents\GitHub\mobile-hosts\converter.php on line 39

Warning: file_get_contents(https://raw.githubusercontent.com/Cybo1927/Hosts/master/Hosts): Failed to open stream: No such file or directory in D:\Documents\GitHub\mobile-hosts\converter.php on line 39
Cybo converted to HOSTS file - see Cybo.txt`

**Comment by r-a-y** [comment]
Converter works for me. You might need to adjust your `php-cli.ini` to enable `extension=php_openssl`. See https://stackoverflow.com/questions/18643572/unable-to-find-the-wrapper-https-with-file-get-contents

Anyway, I've attached a sample conversion for Cybo: https://github.com/r-a-y/mobile-hosts/files/6283191/Cybo.txt

I made some adjustments locally to the converter script so it would block anything with `$popunder`. This means for this rule, `||bitly.com^$popunder`, `bitly.com` would be blocked after conversion, which is a little aggressive...

Also, for rules like `||instagram.com^$domain=wakelet.com`, my script currently strips the `$domain` rule, which means that `instagram.com` would also be blocked.

There are limitations to what you can do with a hosts file. If you need adblock filter support, then you should stick with something like Adguard for full system support. If you are just using a browser on your mobile device, I would suggest either Firefox or Kiwi with the uBlock Origin extension or Brave.

**Comment by peter9811** [comment]
I needed for Android
Actually I use AdAway, I don't like so much AdGuard... My phone had a big battery but I try don't use a lot of process on background 

You know something about another app root for block ads?
Like I said, I use AdAway with custom filters, but some popads and "anti-adblock" appear sometimes

**Comment by r-a-y** [comment]
You can also try setting the private DNS to Adguard DNS: https://kb.adguard.com/en/dns/setup-guide#android

If your Android version is lower than Pie, you can try using AdAway's Log DNS feature to find out which domain is causing the ads: https://github.com/AdAway/AdAway/wiki/LogDNS. If you can find out which domain is causing the ads, you can then block it in AdAway.

Going to close this issue as I'm not going to add it to my list.
