### ISSUE TITLE
Combine them into one?

### ISSUE THREAD

**Issue by Prajwal-Koirala** [r-a-y/mobile-hosts#15]
Hey,
can you please combine them into one.

**Comment by dnmTX** [comment]
The better suggestion is to have separate one that it's combined,not everyone here wants all of them.

**Comment by Prajwal-Koirala** [comment]
Why are you on my dick?

**Comment by r-a-y** [comment]
I agree with dnmTX. I've also replied to a similar question in the past. I prefer to give everyone choice.

If you want a one-size-fits-all approach, use Steven Black's lists or Energized.

**Comment by dalisoft** [comment]
@r-a-y Hey!
Is your block-list is included in lists of @EnergizedProtection's block or @StevenBlack's hosts
