### ISSUE TITLE
c.paypal.com

### ISSUE THREAD

**Issue by dnmTX** [r-a-y/mobile-hosts#18]
@r-a-y for now it's just a possible false-positive. Will need to confirm my findings first before any decisions are made.
I do belive the domain is needed when buying something from Ebay and proceed to pay through PayPal.
Last time was just a rolling circle and wouldn't allow me to make the payment so i ended up whitelisting bunch of domains from various lists that i'm using(was already frustrated enough) just to get through and couldn't confirm which one was the culprit.
On my next purchase i'll have more info,for sure so let's keep this open,for now.
It's originally from [easyprivacy_specific](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific.txt):
https://github.com/easylist/easylist/blob/ce7fc79133f7b671a8892b1324a5fba4b10e6dbf/easyprivacy/easyprivacy_specific.txt#L126
If it's not it,i'll just close this at later date. Thanks 👍

**Comment by r-a-y** [comment]
Thanks for the debugging, dnmTX.

Yeah, I strip the `$script` rule, which causes the entire domain to be blocked. If you find that you cannot buy anything with PayPal, I will write an exception like I did for #17.

I might have to think about ignoring `$script` in my converter, but I'll wait for more false positives before doing so.

**Comment by h1z1** [comment]
Heh.. no idea why this was the first hit for that domain but alas, it should be blocked / neutered.  They are using it to exfiltrate / fingerprint

ex from ```https://c.paypal.com/da/r/fb.js```

```
var t = window.performance;
e.timing.vmStart = Date.now();
var n;
return {
  cores: (e.timing.coresStart = Date.now(), navigator.hardwareConcurrency && (n = navigator.hardwareConcurrency), e.timing.coresTiming = (Date.now() - e.timing.coresStart).toFixed(2), n),
  gpu: function () {
    var t;
    e.timing.gpuStart = Date.now();
    try {
      var n = document.createElement('canvas');
      if (void 0 === n || void 0 === n.getContext) return;
      var i = n.getContext('webgl') || n.getContext('experimental-webgl');
      if (i) {
        if (!('getExtension' in i) || !('getParameter' in i)) return;
        var o = i.getExtension('WEBGL_debug_renderer_info');
        o && (t = {
          vendor: i.getParameter(o.UNMASKED_VENDOR_WEBGL),
          renderer: i.getParameter(o.UNMASKED_RENDERER_WEBGL)
        })
      }
    } catch (t) {
      p(t, e, 'p2VM')
    }
    var a = {
      vendor: null == t ? void 0 : t.vendor,
      renderer: null == t ? void 0 : t.renderer
    };
    return e.timing.gpuTiming = (Date.now() - e.timing.gpuStart).toFixed(2),
    a
  }(),
``` 

That will leak your GPU type/model.

**Comment by dnmTX** [comment]
@r-a-y i'm closing this! I honestly gave up on the whole "convenience" to use PayPal through Ebay. Last time i had to whitelist 4-5 more domains + the aforementioned one here and at the end my chromium browser wouldn't let me do it(links were not secured,blah blah and blah). The link between them is not mintained anymore and it's only left for convenience,so why bother?
Bottom line,whitelisting it here or not wouldn't make any significance difference anyway.
Sorry that it took so long 👍
