### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by hyder365** [r-a-y/mobile-hosts#19]
The line

0.0.0.0 etl.tindersparks.com

is contained within both AdguardMobileAds.txt and AdguardApps.txt

This domain is required to load tinder.com

**Comment by r-a-y** [comment]
Thanks for the report. However, you should post an issue over at Adguard's repository: https://github.com/AdguardTeam/AdguardFilters/issues

Reference this line: https://github.com/AdguardTeam/AdguardFilters/blob/4a34be51937ecd45ff4724348c2e569970446454/MobileFilter/sections/specific_app.txt#L756-L757
