### ISSUE TITLE
Excuse me

### ISSUE THREAD

**Issue by tw-e** [r-a-y/mobile-hosts#2]
@r-a-y 

AdguardMobileAds.txt
Can you manually add these ad hosts to the file to block the blockade?

admob.com
ad.ettoday.net
e.598md.cn
googletagservices.com
vj.quanjingpay.com

 thanks!

**Comment by r-a-y** [comment]
Sorry, I do not manually manage any hosts files.  I just convert existing ones.

If you need to get these domains added, request them over at Adguard's repository - https://github.com/AdguardTeam/AdguardFilters/issues

If you use AdAway on Android, you can easily add your custom domains there.

Hope that helps!
