### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by AliTajelsir** [r-a-y/mobile-hosts#21]
I just wanted to say thank you for these hosts.
I came upon them when I was searching for host files for Adguard. I wanted a lean host fule tailored towards mobile apps (long host files really made my device slow)، and in-app browsers when rarley used. So adguard mobile ads and adguard mobile tracking and sypware hosts were the best choice for me (together are ≈ 1500 domains). In the end I found my self using the same host files as you.
I only added three more domains for ads to disappear completely:
```
pagead2.googleadservices.com
pagead2.googlesyndication.com
googleads.g.doubleclick.net
```

Really thanks for creating these hosts.

**Comment by r-a-y** [comment]
Thanks for the comment!

Regarding those three domains, I also use [AdAway's hosts list](https://adaway.org/hosts.txt) and they contain those domains. I would also recommend that list if you aren't already using that one. I should probably add that to the readme.

**Comment by AliTajelsir** [comment]
Thanks for the suggestion. I also use Adaway,  but I found the before mentioned adguard hosts and three domains suffice for my use case. I disabled any other host source.
Thanks again!

**Comment by r-a-y** [comment]
Good to know. This is precisely why I created these lists to begin with.

Thanks for your testing and feedback! If you come across any other domains in your lean set up, do feel free to post a follow-up comment as I'd be interested to know about them.

**Comment by AliTajelsir** [comment]
Will do, in sha' Allah!.

**Comment by anuraag488** [comment]
@r-a-y a thank you from me also for creating and maintaining this.
