### ISSUE TITLE
AdguardApps.txt isn't updated by script

### ISSUE THREAD

**Issue by vmatrixx** [r-a-y/mobile-hosts#23]
Hello! Thank you for the awesome lists, It's perfect to use them with dnsmasq. Can you please add ability to update AdguardApps.txt via converter.php script?

**Comment by r-a-y** [comment]
I chose not to update that anymore as Adguard Mobile Ads already includes it. See https://github.com/r-a-y/mobile-hosts/commit/e2faee81629466666738bc15179ded418e7c53d2.

I kept AdguardApps.txt in the repo in order not to break any apps using it, but I might remove it sometime down the road.

**Comment by vmatrixx** [comment]
Oh, didn't notice that. Thank you for quick responce!
