### ISSUE TITLE
False positive 

### ISSUE THREAD

**Issue by madmaxpro** [r-a-y/mobile-hosts#25]
g.msn.com is required to save the bitlocker encryption key to Microsoft account.

List using: easylist 3rd party

**Comment by r-a-y** [comment]
Hi @madmaxpro, thanks for the report.

The issue is with EasyPrivacy - https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L876

Please report the problem with them at https://github.com/easylist/easylist/issues.
