### ISSUE TITLE
Hosts

### ISSUE THREAD

**Issue by retta1** [r-a-y/mobile-hosts#3]
Could you convert this filter list ?
https://filters.adtidy.org/extension/chromium/filters/13.txt

**Comment by r-a-y** [comment]
Hi, you might want to use the converted list from Energized Protection as they already converted it:
https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/adguard-turkish-filter.txt

If that isn't good enough, let me know.

**Comment by retta1** [comment]
By checking original adguard filter they have to less hosts. You can compare them both.

**Comment by r-a-y** [comment]
Converted HOSTS files cannot use the special ad filter rules syntax that
popular addons like uBlock Origin and Adguard use.  It's simply not
possible.

The approach that both myself and Energized Protection use is to convert
the simplest of ad filter rules over to the HOSTS file format:
https://github.com/r-a-y/mobile-hosts/blob/master/converter.php#L38

If you're simply looking to block ads in your Android mobile browser,
just use uBlock Origin with Firefox or Kiwi Browser.  Then you can add
whatever ad filter lists you want.

If you want the full ad filter rule support on your mobile device,
including blocking ads in apps, use Adguard for Android, which is a
premium product.

**Comment by retta1** [comment]
I installed adguard premium. Thx
