### ISSUE TITLE
Non-domain entry on AdguardTracking

### ISSUE THREAD

**Issue by nilagangmanok** [r-a-y/mobile-hosts#34]
trk.mail.ru,ping
files.fm%2fl%2femail-pix
emea.focusvision.com%2ftracker%2f
marketing.1password.co%2ftrk%3ft%3d
link.redsift.com%2fe%2fo%2f
marketing.1password.co%2ftrk%3ft%3d
link.redsift.com%2fe%2fo%2f
%2f%2fp.liadm.com%2fimp%3fs%3d
manage.turing.pe%2fanalytics%2fopen%2f
github.com%2fnotifications%2fbeacon%2f
cp.edison.tech%2fapi%2fmailer%2fm%2fimg%2f
link.dissh.com%2fmo%2f
r.ml.reverso.net%2ftr%2fop
33mail.com%2fpage%2fopened
tripadvisor.com%2fmpturl%3fp%3d
tripadvisor.com%2fimg%2fcdsi%2fpartner%2ftransparent_pixel
links.skillbox.ru%2fo%2f
sealfit.ontraport.net%2fo%3f
sendfox.com%2ftrk%2fopen%2f
news.samsung.com%2fus%2f%3fnoti%3d
esputnik.com%2frepository%2fapplications%2fcommons%2fhidden.png
mailchimp.com%2fmctx%2fopens
%2ftrack%2fopen.php%3fu%3d
|mailgun.org
|esv2.com
twitter.com%2fscribe%2fibis%3ft%3d

**Comment by r-a-y** [comment]
Thanks for the report. Most of these entries are because of Adguard's filters to attempt to block email trackers.

Should be addressed in the latest AdguardTracking update. Thanks again!
