### ISSUE TITLE
Masked domains

### ISSUE THREAD

**Issue by rEnr3n** [r-a-y/mobile-hosts#5]
There is an entry at https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt that looks exclusive to adguard. https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/110

Are you having any issues with it? Does it work on your adblocker? I use this list and convert it for dnsmasq. Dnsmasq doesn't like domains starting with a dash so I had to remove it.

**Comment by r-a-y** [comment]
Nice catch, @rEnr3n!  Should be fixed in the latest update.
