### ISSUE TITLE
question about 2b2d906 commit

### ISSUE THREAD

**Issue by patrickdrd** [r-a-y/mobile-hosts#6]
hello, 
about the commit:
https://github.com/r-a-y/mobile-hosts/commit/2b2d9069d9dbfeef0e7cd5c0c6a984ba6742096c

and in the readme:
- [Adguard Mobile Tracking and Spyware](https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileSpyware.txt) (from [Adguard](https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/spyware.txt))
- [Adguard Mobile Tracking and Spyware](https://github.com/AdguardTeam/AdguardFilters/raw/master/SpywareFilter/sections/mobile.txt) (from [Adguard](https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/mobile.txt))

![Clipboard01](https://user-images.githubusercontent.com/24896778/69220351-75006880-0b7d-11ea-9091-1da54fff84c1.jpg)

I think the first link should remain the same:
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileSpyware.txt

since only the 2nd one has changed (the adguard one), yours remains the same, right?

thanks

**Comment by r-a-y** [comment]
Thanks for the report. I noticed this too and should be fixed in the latest commit.
