### ISSUE TITLE
Convert internationalized domains to punycode

### ISSUE THREAD

**Issue by yubiuser** [r-a-y/mobile-hosts#7]
I've been using your AdguardDNS with my pihole installation. Thanks for the great work.
However, there are some (4) domains with Cyrillic letters that [will be rejected by pihole](https://discourse.pi-hole.net/t/encountered-non-critical-sql-warnings/28543/114?u=yubiuser) unless they are formatted to punycode. Could you update your converter to automatically convert all domains with non-ASCII letters to punycode?

P.S There is one additional error as it contains a line with 'mxtads.com:8040' which is also rejected because of the colon.

**Comment by r-a-y** [comment]
Hi, thanks for the report.

I'll add a rule to strip port numbers for the next update.

As for the Cyrillic characters, can you tell me which line numbers the Cyrillic characters show up on?
https://github.com/r-a-y/mobile-hosts/blob/master/AdguardDNS.txt

**Comment by r-a-y** [comment]
@yubiuser - Just checked the link from your first post.  I think I've addressed everything.

Check AdguardDNS.txt for the latest changes and let me know if you still encounter any problems.

**Comment by yubiuser** [comment]
Perfekt, thanks :)

No problems anymore

`
[i] Target: https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
  [✓] Status: Retrieval successful
  [i] 28894 of 28894 domains imported (100.0%)
`
